version: '3.3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
      MYSQL_USER: root
    volumes:
      - dbdata:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
volumes:
  dbdata:
